2023-09-03 10:48:17,816 ERROR: Object reference not set to an instance of an object.
   at AuthenticationJWT.Controllers.LoginController.<>c__DisplayClass7_0.<IsEmailInUse>b__0() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AuthenticationJWT.Controllers.LoginController.<IsEmailInUse>d__7.MoveNext() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
2023-09-03 10:53:30,015 ERROR: Object reference not set to an instance of an object.
   at AuthenticationJWT.Controllers.LoginController.<>c__DisplayClass7_0.<IsEmailInUse>b__0() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AuthenticationJWT.Controllers.LoginController.<IsEmailInUse>d__7.MoveNext() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
2023-09-03 10:57:52,228 ERROR: Object reference not set to an instance of an object.
   at AuthenticationJWT.Controllers.LoginController.<>c__DisplayClass7_0.<IsEmailInUse>b__0() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AuthenticationJWT.Controllers.LoginController.<IsEmailInUse>d__7.MoveNext() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
2023-09-03 11:00:37,619 ERROR: Object reference not set to an instance of an object.
   at AuthenticationJWT.Controllers.LoginController.<>c__DisplayClass7_0.<IsEmailInUse>b__0() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AuthenticationJWT.Controllers.LoginController.<IsEmailInUse>d__7.MoveNext() in F:\Project\MyProject\AuthenticationJWT\AuthenticationJWT\Controllers\LoginController.cs:line 119
